onnx_path: "beyond.onnx"
motion_length: 140 

tau_limit: [
        130.0,
        130.0,
        90.0,
        130.0,
        130.0,
        90.0,
        90.0,
        90.0,
        36.0,
        36.0,
        150.0,
        150.0,
        36.0,
        36.0,
        75.0,
        75.0,
        30.0,
        30.0,
        75.0,
        75.0,
        36.0,
        36.0
    ]

kp_lab: [
        100.0,
        100.0,
        90.0,
        100.0,
        100.0,
        90.0,
        100.0,
        100.0,
        300.0,
        300.0,
        150.0,
        150.0,
        300.0,
        300.0,
        30.0,
        30.0,
        90.0,
        90.0,
        30.0,
        30.0,
        300.0,
        300.0
    ]

kd_lab: [
        5.0,
        5.0,
        3.0,
        5.0,
        5.0,
        3.0,
        5.0,
        5.0,
        3.0,
        3.0,
        7.0,
        7.0,
        3.0,
        3.0,
        3.0,
        3.0,
        3.0,
        3.0,
        3.0,
        3.0,
        3.0,
        3.0
    ]

default_angles_lab: [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0
    ]

action_scale_lab: [
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0
    ]

num_actions: 22
num_obs: 119

mj2lab: [0, 6, 12, 1, 7, 13, 2, 8, 14, 18, 3, 9, 15, 19, 4, 10, 16, 20, 5, 11, 17, 21]